swagger: '2.0'
info:
  title: User API
  version: "0.1.0"
paths:
  /ciserver/updates:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.repository_changed
      summary: The repository has changed.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              command_return:
                type: string
                description: The information is procesing
  /:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.hello
      summary: The repository has changed.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              command_return:
                type: string
                description: The information is procesing
