
version: '3'
services:
    registry:
        image: registry:2
        restart: always
        container_name: Registry_Server
        volumes:
            - './docker_data/certs:/certs'
        environment:
            - 'REGISTRY_HTTP_ADDR=0.0.0.0:443'
            - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
            - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
        ports:
            - '443:443'
    ci_server:
        build: CI_Server
        container_name: CI_Server
        volumes:
          - //var/run/docker.sock:/var/run/docker.sock
        environment:
          - 'CI_SERVER_HTTP_ADDR=0.0.0.0:8080'
        ports:
          - '8080:8080'
    ngrok:
        image: wernight/ngrok
        ports:
          - '0.0.0.0:4040:4040'
        links:
          - ci_server
        environment:
NGROK_PORT: ci_server:8080
